### PR TITLE
Update modDesc.xml

### PR DESCRIPTION
**Pull request by KITT3000**
Added PL translation

### CODE REVIEW

**Comment by jDanek** [comment]
Thank you for the improvements. I update on ModHub but I do not know how long it will take to update it. Please use spaces instead of tabs.

**Comment by KITT3000** [comment]
@jDanek To tell you the truth, you should use a tab instead of a space, this reduces the number of characters and makes it easier to organize.

**Comment by jDanek** [comment]
@KITT3000 I'm mainly programming in PHP, which uses more than 4 spaces instead of tab, which governs the PSR-2 standard, so I use spaces. I do not want to change habits.

**Comment by KITT3000** [comment]
@jDanek I do not know in which editor you work, but even Notepad++ itself, in XML coding, creates a tab after creating a new line. Maybe the space is more convenient but I think that only up to ~10 columns, if there will be more of them, you need to press the space a bit. But I will try to remember for the future to switch settings to spaces from the default tab in your repositories.

**Comment by jDanek** [comment]
Thank you.

**Pull request merged**
